//
// Autogenerated by Natalie - Storyboard Generator
// by Marcin Krzyzanowski http://krzyzanowskim.com
//
import Cocoa

// MARK: - Storyboards

extension NSStoryboard {
    func instantiateViewController<T: NSWindowController>(ofType type: T.Type) -> T? where T: IdentifiableProtocol {
        let instance = type.init()
        if let identifier = instance.storyboardIdentifier {
            return self.instantiateController(withIdentifier: identifier) as? T
        }
        return nil
    }

    func instantiateViewController<T: NSViewController>(ofType type: T.Type) -> T? where T: IdentifiableProtocol {
        let instance = type.init()
        if let identifier = instance.storyboardIdentifier {
            return self.instantiateController(withIdentifier: identifier) as? T
        }
        return nil
    }

}

protocol Storyboard {
    static var storyboard: NSStoryboard { get }
    static var identifier: NSStoryboard.Name { get }
}

struct Storyboards {

    struct Main: Storyboard {

        static let identifier = "Main"

        static var storyboard: NSStoryboard {
            return NSStoryboard(name: self.identifier, bundle: nil)
        }

        static func instantiateInitialController() -> NSWindowController {
            return self.storyboard.instantiateInitialController() as! NSWindowController
        }

        static func instantiateController(withIdentifier identifier: NSStoryboard.SceneIdentifier) -> NSWindowController {
            return self.storyboard.instantiateController(withIdentifier: identifier) as! NSWindowController
        }

        static func instantiateViewController<T: NSWindowController>(ofType type: T.Type) -> T? where T: IdentifiableProtocol {
            return self.storyboard.instantiateViewController(ofType: type)
        }

        static func instantiateController(withIdentifier identifier: NSStoryboard.SceneIdentifier) -> NSViewController {
            return self.storyboard.instantiateController(withIdentifier: identifier) as! NSViewController
        }

        static func instantiateViewController<T: NSViewController>(ofType type: T.Type) -> T? where T: IdentifiableProtocol {
            return self.storyboard.instantiateViewController(ofType: type)
        }
    }
}

// MARK: - ReusableKind
enum ReusableKind: String, CustomStringConvertible {
    case tableViewCell = "tableViewCell"
    case collectionViewCell = "collectionViewCell"

    var description: String { return self.rawValue }
}

// MARK: - SegueKind
enum SegueKind: String, CustomStringConvertible {
    case relationship = "relationship"
    case show = "show"
    case presentation = "presentation"
    case embed = "embed"
    case unwind = "unwind"
    case push = "push"
    case modal = "modal"
    case popover = "popover"
    case replace = "replace"
    case custom = "custom"

    var description: String { return self.rawValue }
}

// MARK: - IdentifiableProtocol

public protocol IdentifiableProtocol: Equatable {
    var storyboardIdentifier: NSStoryboard.SceneIdentifier? { get }
}

// MARK: - SegueProtocol

public protocol SegueProtocol {
    var identifier: NSStoryboardSegue.Identifier? { get }
}

public func ==<T: SegueProtocol, U: SegueProtocol>(lhs: T, rhs: U) -> Bool {
    return lhs.identifier == rhs.identifier
}

public func ~=<T: SegueProtocol, U: SegueProtocol>(lhs: T, rhs: U) -> Bool {
    return lhs.identifier == rhs.identifier
}

public func ==<T: SegueProtocol>(lhs: T, rhs: NSStoryboardSegue.Identifier) -> Bool {
    return lhs.identifier == rhs
}

public func ~=<T: SegueProtocol>(lhs: T, rhs: NSStoryboardSegue.Identifier) -> Bool {
    return lhs.identifier == rhs
}

public func ==<T: SegueProtocol>(lhs: NSStoryboardSegue.Identifier, rhs: T) -> Bool {
    return lhs == rhs.identifier
}

public func ~=<T: SegueProtocol>(lhs: NSStoryboardSegue.Identifier, rhs: T) -> Bool {
    return lhs == rhs.identifier
}

/*extension NSStoryboardSegue.Identifier: ExpressibleByStringLiteral {
    public typealias StringLiteralType = String
    public init(stringLiteral value: StringLiteralType) {
        self.init(rawValue: value)
    }
}

public func ==<T: SegueProtocol>(lhs: T, rhs: String) -> Bool {
    return lhs.identifier? == rhs
}

public func ~=<T: SegueProtocol>(lhs: T, rhs: String) -> Bool {
    return lhs.identifier? == rhs
}

public func ==<T: SegueProtocol>(lhs: String, rhs: T) -> Bool {
    return lhs == rhs.identifier?
}

public func ~=<T: SegueProtocol>(lhs: String, rhs: T) -> Bool {
    return lhs == rhs.identifier?
}*/

// MARK: - ReusableViewProtocol
public protocol ReusableViewProtocol: IdentifiableProtocol {
    var viewType: NSView.Type? { get }
}

public func ==<T: ReusableViewProtocol, U: ReusableViewProtocol>(lhs: T, rhs: U) -> Bool {
    return lhs.storyboardIdentifier == rhs.storyboardIdentifier
}

// MARK: - Protocol Implementation
extension NSStoryboardSegue: SegueProtocol {
}

// MARK: - NSViewController extension
extension NSViewController {
    func perform<T: SegueProtocol>(segue: T, sender: Any?) {
        if let identifier = segue.identifier {
            performSegue(withIdentifier: identifier, sender: sender)
        }
    }

    func perform<T: SegueProtocol>(segue: T) {
        perform(segue: segue, sender: nil)
    }
}
// MARK: - NSWindowController extension
extension NSWindowController {
    func perform<T: SegueProtocol>(segue: T, sender: Any?) {
        if let identifier = segue.identifier {
            performSegue(withIdentifier: identifier, sender: sender)
        }
    }

    func perform<T: SegueProtocol>(segue: T) {
        perform(segue: segue, sender: nil)
    }
}

// MARK: - DestinationViewController

// MARK: - DestinationViewController

// MARK: - FromViewController
extension NSStoryboardSegue {
    func selection() -> FromViewController.Segue? {
        if let identifier = self.identifier {
            return FromViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}
extension FromViewController {

    enum Segue: NSStoryboardSegue.Identifier, CustomStringConvertible, SegueProtocol {
        case configured = "configured"
        case chidwindow = "chidwindow"
        case splitview = "splitview"
        case customanimator = "customanimator"
        case replace = "replace"

        var kind: SegueKind? {
            switch self {
            case .configured:
                return SegueKind(rawValue: "custom")
            case .chidwindow:
                return SegueKind(rawValue: "custom")
            case .splitview:
                return SegueKind(rawValue: "custom")
            case .customanimator:
                return SegueKind(rawValue: "custom")
            case .replace:
                return SegueKind(rawValue: "custom")
            }
        }

        var destination: AnyObject.Type? {
            switch self {
            case .configured:
                return DestinationViewController.self
            case .chidwindow:
                return DestinationViewController.self
            case .splitview:
                return NSSplitViewController.self
            case .customanimator:
                return DestinationViewController.self
            case .replace:
                return DestinationViewController.self
            }
        }

        var identifier: NSStoryboardSegue.Identifier? { return self.rawValue }
        var description: String { return "\(self.rawValue)" }
    }

}

// MARK: - DestinationSplitViewController
extension NSStoryboardSegue {
    func selection() -> DestinationSplitViewController.Segue? {
        if let identifier = self.identifier {
            return DestinationSplitViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}
extension DestinationSplitViewController {

    enum Segue: NSStoryboardSegue.Identifier, CustomStringConvertible, SegueProtocol {
        case rowdetail = "rowdetail"

        var kind: SegueKind? {
            switch self {
            case .rowdetail:
                return SegueKind(rawValue: "custom")
            }
        }

        var destination: AnyObject.Type? {
            switch self {
            case .rowdetail:
                return NSViewController.self
            }
        }

        var identifier: NSStoryboardSegue.Identifier? { return self.rawValue }
        var description: String { return "\(self.rawValue)" }
    }

}

// MARK: - SplitViewController

